main_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
path('', views.home, name='home'),
path('about/', views.about, name='about'),
path('cards/', views.cards_index, name='index'),
path('cards/<int:card_id>/', views.cards_detail, name='detail'),
path('cards/create/', views.CardCreate.as_view(), name='cards_create'),
path('cards/<int:pk>/update/', views.CardUpdate.as_view(), name='cards_update'),
path('cards/<int:pk>/delete/', views.CardDelete.as_view(), name='cards_delete'),
path('cards/<int:card_id>/add_selling/', views.add_selling, name='add_selling'),
path('accounts/signup/', views.signup, name='signup'),
]

tcg_binder/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
# Create your models here.
PRICE = (
    ('H', 'High'),
    ('M', 'Mid'),
    ('L', 'Low')
)

class Cards(models.Model):
    name = models.CharField(max_length=100)
    type = models.CharField(max_length=100)
    hp = models.IntegerField()
    move_name_1 = models.CharField(max_length=100)
    move_name_2 = models.CharField(max_length=100)
    weakness_type = models.CharField(max_length=100)
    card_type = models.CharField(max_length=100)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    def detail(self):
        return reverse('cards_detail', kwargs={'card_id': self.id})

class Selling(models.Model):
    date = models.DateField('Date')
    price = models.IntegerField(
        choices=PRICE,
        default=PRICE[0][0]
    )
    card = models.ForeignKey(Cards, on_delete=models.CASCADE)
    def __str__(self):
        return f"{self.get_price_display()} on {self.date}"
    class Meta:
        ordering = ['-date']

main_app/forms.py
from django.forms import ModelForm
from .models import Selling

class SellingForm(ModelForm):
  class Meta:
    model = Selling
    fields = ['date', 'price']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from main_app.models import Cards
from .forms import SellingForm
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

@login_required
def cards_index(request):
  cards = Cards.objects.filter(user=request.user)
  return render(request, 'cards/index.html', { 'cards': cards})


@login_required
def cards_detail(request, card_id):
  cards = Cards.objects.get(id=card_id)
  selling_form = SellingForm()
  return render(request, 'cards/detail.html', {
    'cards': cards, 'selling_form': selling_form
  })

@login_required
def add_selling(request, card_id):
  form = SellingForm(request.POST)
  if form.is_valid():
    new_selling = form.save(commit=False)
    new_selling.card_id = card_id
    new_selling.save()
  return redirect('detail', card_id=card_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

class CardCreate(LoginRequiredMixin, CreateView):
  model = Cards
  fields = ['name', 'type', 'hp', 'move_name_1', 'move_name_2', 'weakness_type', 'card_type' ]
  success_url = '/cards/'
  
  def form_valid(self, form):
      form.instance.user = self.request.user
      return super().form_valid(form)

class CardUpdate(LoginRequiredMixin, UpdateView):
  model = Cards
  fields = '__all__'
  success_url = '/cards/'

class CardDelete(LoginRequiredMixin, DeleteView):
  model = Cards
  success_url = '/cards/'

main_app/templates/about.html
{% extends 'base.html' %} {% block content %}

<h1>Did you catch them all?</h1>
<hr />
<p>Caught this pokemon is an online binder to show off your collection of pokemon cards and also put them up for
    auction for buyers! </p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>TCG Binder</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
    <link href="//fonts.cdnfonts.com/css/pokemon-solid?styles=24573" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</head>

<body>

    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul class="nav-color">
                    <li>
                        <a href="/" class="left brand-logo" style="color:#039be5"> Caught This Pokemon</a>
                    </li>
                </ul>
                <ul class="right" style="color:#039be5">
                    <li><a href="{% url 'about' %}" style="color:#039be5">About</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'cards_create' %}" style="color:#039be5">Caught Another One?</a></li>
                    <li><a href="{% url 'index' %}" style="color:#039be5">View My Cards</a></li>
                    <li><a href="{% url 'logout' %}" style="color:#039be5">Log Out</a></li>
                    {% else %}
                    <li><a href="{% url 'signup' %}" style="color:#039be5">Sign Up</a></li>
                    <li><a href="{% url 'login' %}" style="color:#039be5">Log In</a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">{% block content %} {% endblock %}</main>
    <footer class="page-footer">
        <div class="right">
            All Rights Reserved, © 2019 Caught this Pokemon
        </div>
    </footer>
</body>

</html>

main_app/templates/cards/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Card Info</h1>

<div class="card">
    <div class="card-content">
        <span class="card-title">{{ cards.name }}</span>
        <p>Type: {{ cards.type }}</p>
        <p>Hp: {{ cards.hp }}</p>
        <p>Move 1: {{ cards.move_name_1 }}</p>
        <p>Move 2: {{ cards.move_name_2 }}</p>
        <p>Weakness: {{ cards.weakness_type }}</p>
        <p>Card Type: {{ cards.card_type }}</p>
        <div class="card-action">
            <a href="{% url 'cards_update' cards.id %}" class="edit">Edit</a>
            <a href="{% url 'cards_delete' cards.id %}" classs="delete">Delete</a>
        </div>
    </div>
</div>


<div class="col s6">
    <!-- <form action="{% url 'add_selling' cards.id %}" method="POST">
        {% csrf_token %} {{ selling_form.as_p }} -->
    <!-- <input type="submit" class="btn" value="Add Price Point" /> -->
    </form>
    <table class="striped">
        <thead>
            <!-- <tr>
                <th>Date</th>
                <th>Price Range</th>
            </tr> -->
        </thead>
        <tbody>
            {% for selling in card.selling_set.all %}
            <tr>
                <!-- <td>{{selling.date}}</td>
                <td>{{selling.get_price_display}}</td> -->
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
<!-- <script>
    var dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
        format: 'yyyy-mm-dd',
        defaultDate: new Date(),
        setDefaultDate: true,
        autoClose: true
    });
    var selectEl = document.getElementById('id_price');
    M.FormSelect.init(selectEl);
</script> -->
{% endblock %}

main_app/templates/cards/index.html
{% extends 'base.html' %} {% block content %}

<h1>Card Collection</h1>

{% for card in cards %}

<div class="card">
    <a href="{% url 'detail' card.id %}">
        <div class="card-content">
            <span class="card-title">{{ card.name }}</span>
            <p>Type: {{ card.type }}</p>
            <p>Hp: {{ card.hp }}</p>
            <p>Move 1: {{ card.move_name_1 }}</p>
            <p>Move 2: {{ card.move_name_2 }}</p>
            <p>Weakness: {{ card.weakness_type }}</p>
            <p>Card Type: {{ card.card_type }}</p>

        </div>
    </a>
</div>


{% endfor %} {% endblock %}

main_app/templates/home.html
{% extends 'base.html' %} {% block content %}

<h1>Hello Trainer</h1>
<hr />
<p>Welcome to caught this pokemon! An online binder used to track your pokemon cards to show off to your friends! Can
    you catch them all? Prove it!
</p>
{% endblock %}

main_app/templates/main_app/cards_confirm_delete.html
{% extends 'base.html' %} {% block content %}
<h1>Delete Card</h1>

<h4>
    Are you sure you want to delete
    <span class="orange-text">{{ card.name }}</span>?
</h4>
<br />
<br />
<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn" />
    <br />
    <br />
    <a href="{% url 'detail' object.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/cards_form.html
{% extends 'base.html' %} {% block content %}


{% if object %}
<h1>Edit <span class="rgb(255, 77, 0)">{{object.name}}</span></h1>
{% else %}
<h1>Add card</h1>
{% endif %}
<form action="" method="post"></span>

    {% csrf_token %}
    <table>

        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn" />
</form>
{% endblock %}